### ISSUE TITLE
"TypeError: exports.overwriteWith is not a function" when using with Jest

### ISSUE THREAD

**Issue by pwmcintyre** [alexfernandez/loadtest#159] opened 2019-02-15 03:15 UTC
In my project we like to run our tests within Jest - so I thought I'd try loadtest within Jest, but I get an error which I can't seem to resolve - seeking assistance.

To reproduce:

package.json
```json
{
  "name": "example",
  "dependencies": {
    "@types/jest": "^24.0.5",
    "@types/node": "^11.9.4",
    "jest": "^24.1.0",
    "loadtest": "^3.0.6",
    "ts-jest": "^23.10.5",
    "typescript": "^3.3.3"
  },
  "scripts": {
    "test": "jest"
  }
}
```

Setup
```shell
# setup npm
npm i

# setup typescript
./node_modules/typescript/bin/tsc --init

# setup jest
printf "module.exports = { preset: 'ts-jest', testEnvironment: 'node' }" > jest.config.js
```

./test.ts
```TypeScript
import loadtest from "loadtest"
import { promisify } from "util"

const loadTest = promisify( loadtest.loadTest )

test("loadtest", () => {

    const options: loadtest.LoadTestOptions = {
        url: "https://www.google.com",
        method: "GET",
        maxRequests: 1,
    }

    return expect( loadTest(options) ).resolves.toMatchSnapshot()

})
```

run
```shell
./node_modules/jest/bin/jest.js
```

error
```
 FAIL  ./test.ts
  ● Test suite failed to run

    TypeError: exports.overwriteWith is not a function

    > 1 | import loadtest from "loadtest"
        | ^
      2 | import { promisify } from "util"
      3 | 
      4 | const loadTest = promisify( loadtest.loadTest )

      at Object.<anonymous> (node_modules/prototypes/index.js:15:9)
      at Object.<anonymous> (node_modules/loadtest/lib/loadtest.js:10:1)
      at Object.<anonymous> (node_modules/loadtest/index.js:10:18)
      at Object.<anonymous> (test.ts:1:1)
```

Edit: Fixed steps to reproduce

**Comment by alexfernandez** [comment] 2019-02-16 21:53
Hum, that is weird. It appears as if something is preventing prototypes from modifying the `Object` prototype. Which version of Node.js and TypeScript are you using?

**Comment by pwmcintyre** [comment] 2019-02-18 02:20
Versions:
```
$ node --version
v8.10.0

$ ./node_modules/typescript/bin/tsc --version
Version 3.3.3
```

I've fixed up the reproduction steps, i missed out some tsc and jest setup

I'm out of my depth with this one, I might have to find another way, but it would be great to get working

**Comment by alexfernandez** [comment] 2019-02-19 17:46
Thanks to your detailed instructions I have reproduced this issue, it is caused by my use of the prototypes library which adds some new functions to built-in prototypes: TypeScript does not like it :'(

I am out of my depth here too. Maybe some of the contributors to TypeScript bindings and examples can lend us a hand? cc @GregOnNet @AmirSasson

**Comment by GregOnNet** [comment] 2019-02-19 21:06
Hi,

I do not think that this issue is directly related to TypeScript but maybe to Jest.
I found out that `exports.overwriteWith(objectLib)` is called before `var objectLib = require('./lib/object.js');
`

Please notice that this is just an assumption. I am not sure either what the root cause is.


## Workaround

If I patch `exports` inside `index.js` the test is executed as expected.

```js
// prototypes/index.js
'use strict';

/**
 * Export all prototypes.
 * (C) 2013 Alex Fernández.
 */

// requires
require('./lib/string.js');
require('./lib/array.js');

var mathLib = require('./lib/math.js');
var objectLib = require('./lib/object.js');

// exports
exports.overwriteWith = function(overwriter) {
  for (let key in overwriter) {
    let value = overwriter[key];
    if (value !== undefined) {
      this[key] = value;
    }
  }
  return this;
};

exports.overwriteWith(objectLib);
exports.overwriteWith(mathLib);
```

**Comment by alexfernandez** [comment] 2019-02-20 16:01
@pwmcintyre Can you use a different testing library and see if the problem persists?

**Comment by Sroy0202** [comment] 2020-10-21 05:31
TypeError: user.generateAuthToken is not a function. I also have this type of problem

**Comment by alexfernandez** [comment] 2023-08-17 18:05
This issue should be solved in recent versions, as there is no dependency on `prototypes`. Closing, please reopen if needed.

**Closed by alexfernandez** 2023-08-17 18:05 UTC
